#!/usr/bin/python

import gobject

import sys
import dbus
import dbus.service
import dbus.mainloop.glib
import os.path
from optparse import OptionParser

class Agent(dbus.service.Object):
    def __init__(self, conn=None, obj_path=None, verbose=False):
        dbus.service.Object.__init__(self, conn, obj_path)
        self.verbose = verbose

    @dbus.service.method("org.openobex.DisplayImage",
                    in_signature="su", out_signature="")
    def DisplayImage(self, path, id):
        print "Display Image: path = " + str(path) + ", id = " + str(id)
        return

tasks = []

if  __name__ == '__main__':

    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    bus = dbus.SessionBus()
    mainloop = gobject.MainLoop()

    path = "/test/rdagent"
    agent = Agent(bus, path, True)
	
    client = dbus.Interface(bus.get_object("org.openobex.RDManager",
                            "/rdmanager"), "org.openobex.RDManager.RDManager")

    print client

    session_path = client.RegisterAgent(path)

    mainloop.run()
